services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.adianti-db
    environment:
      POSTGRES_DB: atendente
      POSTGRES_USER: atendente
      POSTGRES_PASSWORD: atendente123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./admin-panel/app/database:/docker-entrypoint-initdb.d:ro  # Copia os arquivos SQL para inicialização do PostgreSQL
    ports:
      - "5432:5432"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=atendente
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n123
      - DB_POSTGRESDB_SCHEMA=n8n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - ollama
    restart: unless-stopped

  adianti:
    build:
      context: ./admin-panel
      dockerfile: ../Dockerfile.adianti
    container_name: adianti
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: atendente
      DATABASE_USER: atendente
      DATABASE_PASSWORD: atendente123
    volumes:
      - ./admin-panel:/var/www/html
      - ./admin-panel/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:9.10.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - "5050:80"  # Acessível via http://localhost:5050
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json  # Montar o arquivo de configuração
volumes:
  postgres_data:
  pgadmin_data:  # Definição do volume que estava faltando
  ollama_data:
  pg_data:
  n8n_data:
